src/Entity/Work.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkRepository")
 */
class Work
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="smallint")
     */
    private $timeNeeded;

    /**
     * @ORM\Column(type="boolean")
     */
    private $completion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Visit", inversedBy="works")
     */
    private $visit;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TimeTable", inversedBy="works")
     */
    private $timeTable;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Added;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTimeNeeded(): ?int
    {
        return $this->timeNeeded;
    }

    public function setTimeNeeded(int $timeNeeded): self
    {
        $this->timeNeeded = $timeNeeded;

        return $this;
    }

    public function getCompletion(): ?bool
    {
        return $this->completion;
    }

    public function setCompletion(bool $completion): self
    {
        $this->completion = $completion;

        return $this;
    }

    public function getVisit(): ?Visit
    {
        return $this->visit;
    }

    public function setVisit(?Visit $visit): self
    {
        $this->visit = $visit;

        return $this;
    }

    public function getTimeTable(): ?TimeTable
    {
        return $this->timeTable;
    }

    public function setTimeTable(?TimeTable $timeTable): self
    {
        $this->timeTable = $timeTable;

        return $this;
    }

    public function getAdded(): ?bool
    {
        return $this->Added;
    }

    public function setAdded(bool $Added): self
    {
        $this->Added = $Added;

        return $this;
    }
}

src/Controller/WorkController.php
<?php

namespace App\Controller;

use App\Entity\Work;
use App\Entity\TimeTable;
use App\Entity\User;
use App\Entity\Car;
use App\Entity\Visit;
use App\Form\WorkAddType;
use App\Form\EditWorkType;
use App\Form\WorkCompletionType;
use App\Form\ChangeTimeNeededType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class WorkController extends AbstractController
{
    /**
     * @Route("/works/index", name="works")
     */
    public function showWorksMenu(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $this->getUser();
        $works = $em->getRepository('App:Work')->findAll();
        /*if(in_array('ROLE_ADMIN', $user->getRoles()) ||
            in_array('ROLE_MECHANIC', $user->getRoles()))
            $works = $em->getRepository('App:Work')->findAll();

        else {
            $works = $em->getRepository('App:Work')
                ->findBy(
                    ['user' => $user->getId()]
                );
        }*/
        return $this->render('works/index.html.twig', [
            'works' => $works,
        ]);
    }
    /**
     * @Route("/works/addWork", name="addWork")
     */
    public function addWork(Request $request)
    {
        $work = new Work();
        $em = $this->getDoctrine()->getManager();
        $visits = $em->getRepository('App:Visit')->findAll();

        $form = $this->createForm(WorkAddType::class, null, array(
            'visits' => $visits,
        ));
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $visit = $form['visit']->getData();

            $work->setType($form['type']->getData());
            $work->setDescription($form['description']->getData());
            $work->setTimeNeeded($form['timeNeeded']->getData());
            $work->setCompletion(0);
            $work->setAdded(0);
            $work->setVisit($form['visit']->getData());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($work);
            $entityManager->flush();

            return $this->redirectToRoute('works');
        }
        return $this->render('works/addWork.html.twig', [
            'visits' => $visits,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/works/editWork/{id}", name="editWork")
     */
    public function editWork(Request $request, Work $work)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(EditWorkType::class, $work);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em->persist($work);
            $em->flush();

        return $this->redirectToRoute('works');
        }
        return $this->render('works/editWork.html.twig', [
            'work' => $work,
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/works/deleteWork/{id}", name="deleteWork")
     */
    public function deleteWork(Request $request, Work $work)
    {

        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        if(in_array('ROLE_ADMIN', $user->getRoles()) ||
            in_array('ROLE_MECHANIC', $user->getRoles()) &&
            in_array('1', $work->getCompletion())){
            $em->remove($work);
            $em->flush();
            return $this->redirectToRoute('works');
        }
        
    }
    /**
     * @Route("/works/changeTimeNeeded\{id}", name="changeTimeNeeded")
     */
    public function changeTimeNeeded(Request $request, Work $work)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(ChangeTimeNeededType::class, $work);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $work->setTimeNeeded($form['timeNeeded']->getData());

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($work);
        $entityManager->flush();

        return $this->redirectToRoute('works');
        }
        return $this->render('works/changeTimeNeeded.html.twig', [
            'form' => $form->createView(),
        ]);
    }
     /**
     * @Route("/works/confirmCompletion/{id}", name="confirmCompletion")
     */
    public function confirmCompletion(Request $request, Work $work)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(WorkCompletionType::class, $work);
        $form->handleRequest($request);

        $work->setCompletion(1);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($work);
        $entityManager->flush();

        return $this->redirectToRoute('works');
       
    }
     /**
     * @Route("/works/timeTable", name="timeTable")
     */
    public function timeTable(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();

        $works = $em->getRepository('App:Work')->findAll();
        /*if(in_array('ROLE_ADMIN', $user->getRoles()) ||
            in_array('ROLE_MECHANIC', $user->getRoles()))
            $works = $em->getRepository('App:Work')->findAll();

        else {
            $works = $em->getRepository('App:Work')
                ->findBy(
                    ['user' => $user->getId()]
                );
        }*/
        return $this->render('works/timeTable.html.twig', [
            'works' => $works,
        ]);
    }
    public function addToTable()
    {
        
    }
}

templates/works/addWork.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<script>
        function goBack(){
            window.history.back()
        }
    </script>
 <center><h2>Darbo pridėjimo forma</h2></center>
    <br>
    <div class="container">
   {{ form_start(form)}}
      <center>{{ form_widget(form, { 'attr': {'style': 'width: 30%'} }) }}
      <button type="submit" class="btn btn-success">Pridėti darbą</button>
      &emsp;&emsp;&emsp;&emsp;
      <button onclick="goBack()" class="btn btn-warning">Grįžti atgal</button>
      </center>
     {{ form_end(form) }}
     </div>

{% endblock %}

templates/works/changeTimeNeeded.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<script>
        function goBack(){
            window.history.back()
        }
    </script>
<center><h2>Laiko įverčių keitimo forma</h2></center>
<br>
<div class="container">
    {{ form_start(form)}}
         <center>{{ form_widget(form, { 'attr': {'style': 'width: 30%'} }) }}
            <button type="submit" class="btn btn-success">Atnaujinti</button>
        &emsp;&emsp;&emsp;&emsp;
        <button onclick="goBack()" class="btn btn-warning">Grįžti atgal</button>
        </center>
    {{ form_widget(form) }}
</div>
{% endblock %}

templates/works/editWork.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<script>
        function goBack(){
            window.history.back()
        }
    </script>
<center><h2>Redaguoti darbą</h2></center>
<br>
 <div class="container">
    {{ form_start(form)}}
        <center>{{ form_widget(form, { 'attr': {'style': 'width: 30%'} }) }}
           <button type="submit" class="btn btn-success">Pridėti darbą</button>
        &emsp;&emsp;&emsp;&emsp;
        <button onclick="goBack()" class="btn btn-warning">Grįžti atgal</button>
        </center>
    {{ form_widget(form) }}
</div>
       

{% endblock %}

templates/works/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<br>
<center><div class="btn-group">
{% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_MECHANIC'))%}
    <li><a href="{{ path('addWork') }}" class="btn btn-info">Pridėti darbą</a></li>
{% endif %}
</div></center>
<br><br><br>
<center>
<div style="max-width:70%;">
<table class="table table-striped table-hover table-bordered">

    <tr>
        <td>#</td>
        <td>Auto nr.</td>
        <td>Darbo tipas</td>
        <td>Aprašymas</td>
        <td>Skirtas laikas, (val.)</td>
        <td>Progresas</td>
        <td></td>
    </tr>
 {% for work in works %}
            <tr>
            <th>{{ loop.index }}</th>
            <td>{% if (work == null) or (work.visit == null) %}
                    null
                {% else %}
                {{ work.visit.car.registrationPlate }}
                {% endif %}</td>
            <td>{{ work.type}}</td>
            <td>{{ work.description}}</td>
            <td>{{ work.timeNeeded}}</td>
            <td>{% if (work.completion == 1) %}
                    Baigtas
                {% endif %}
            </td>
            <td>
            {% if (is_granted('ROLE_ADMIN')) or (is_granted('ROLE_MECHANIC')) %}
                    <a href="{{ path('editWork', {id: work.id}) }}">
                        <button type="button" class="btn btn-secondary">Redaguoti</button>
                    </a>
                    <a href="{{ path('changeTimeNeeded', {id: work.id}) }}">
                        <button type="button" class="btn btn-secondary">Keisti laiką</button>
                    </a>
                    <a href="{{ path('deleteWork', {id: work.id}) }}">
                        <button type="button" class="btn btn-danger">Šalinti</button>
                    </a>
                    {% endif %}
                    {% if (is_granted('ROLE_ADMIN')) or (is_granted('ROLE_USER')) %}
                    <a href="{{ path('confirmCompletion', {id: work.id}) }}">
                        <button type="button" class="btn btn-success" onclick='return confirm("Patvirtinkite")'>Darbas atliktas</button>
                    </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
     {% if (is_granted('ROLE_ADMIN')) or (is_granted('ROLE_MECHANIC')) %}
    <li><a href="{{ path('timeTable') }}" class="btn btn-info btn-lg btn-block">Tvarkaraštis</a></li>
    {% endif %}
    </div>
    </center>
{% endblock %}

templates/works/timeTable.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
 <br>
 <center><h2>{% if app.user %} Tvarkaraštis vartotojui: {{ app.user.username }} {% endif %}</h2></center>
<center>
<div style="max-width:70%;">
<table class="table table-striped table-hover table-bordered">

    <tr>
        <td>Auto nr.</td>
        <td>Darbo tipas</td>
        <td>Aprašymas</td>
        <td>Skirtas laikas, (val.)</td>
        <td></td>
    </tr>
 {% for work in works %}
 {% if work.added == '0' %}
            <tr>
            <td>{{ work.visit.car.registrationPlate }}</td>
            <td>{{ work.type}}</td>
            <td>{{ work.description}}</td>
            <td>{{ work.timeNeeded}}</td>
            </td>
            <td>
            {% if (is_granted('ROLE_ADMIN')) or (is_granted('ROLE_MECHANIC')) %}
                    <a href="{{ path('editWork', {id: work.id}) }}">
                        <button type="button" class="btn btn-secondary">Rinktis darbą</button>
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
    </div>
    </center>
{% endblock %}